### ISSUE TITLE
mixed compression schemes of various rootfs

### ISSUE THREAD

**Issue by nickdesaulniers** [groeck/linux-build-test#1]
Hi @groeck ,
I noticed that rootfs/x86_64/rootfs.ext2 was not compressed whereas rootfs/arm64/rootfs.ext2.gz was.  There seems to be a good mix of compressed vs not.  Could you compress all? That would make automation using these fs images a little simpler.

**Comment by groeck** [comment]
For the most part old root file systems are uncompressed, new ones are. As I have time, I am replacing uncompressed root file systems with compressed ones. The infrastructure has no issues dealing with both, so this is low priority. It is less than perfect either way, since while compressed format saves space, it also requires decompression for each run. It would be more efficient to decompress, cache the decompressed files in some well defined place, and use the -snapshot qemu parameter to make sure that the original file is not modified. All a matter of time, or rather the lack of it.
The same is true for the content of the root file systems. As I have time, I replace them with newly generated root file systems built with buildroot. Typically this goes along with compressing them.

**Comment by groeck** [comment]
All root file systems should now be compressed. Uncompressed root file systems are cached in /var/cache/buildroot/\<arch\> and reused.

**Comment by nickdesaulniers** [comment]
Thanks @groeck !
